name: Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install --ignore-engines --frozen-lockfile
      - run: yarn run build
